#ifndef SCENE_BASE_H
#define SCENE_BASE_H

#include "Scene.h"
#include "Mtx44.h"
#include "Camera.h"
#include "Mesh.h"
#include "MatrixStack.h"
#include "Light.h"
#include "GameObject.h"
#include <vector>

class SceneBase : public Scene
{
	enum UNIFORM_TYPE
	{
		U_MVP = 0,
		U_MODELVIEW,
		U_MODELVIEW_INVERSE_TRANSPOSE,
		U_MATERIAL_AMBIENT,
		U_MATERIAL_DIFFUSE,
		U_MATERIAL_SPECULAR,
		U_MATERIAL_SHININESS,
		U_LIGHTENABLED,
		U_NUMLIGHTS,
		U_LIGHT0_TYPE,
		U_LIGHT0_POSITION,
		U_LIGHT0_COLOR,
		U_LIGHT0_POWER,
		U_LIGHT0_KC,
		U_LIGHT0_KL,
		U_LIGHT0_KQ,
		U_LIGHT0_SPOTDIRECTION,
		U_LIGHT0_COSCUTOFF,
		U_LIGHT0_COSINNER,
		U_LIGHT0_EXPONENT,
		U_COLOR_TEXTURE_ENABLED,
		U_COLOR_TEXTURE,
		U_TEXT_ENABLED,
		U_TEXT_COLOR,
		U_TOTAL,
	};
public:
	enum GEOMETRY_TYPE
	{
		GEO_AXES,
		GEO_TEXT,
		GEO_BALL,
		GEO_CUBE,
		GEO_MAXCUBE,
		GEO_ENERGYCUBE,
		GEO_MAXENERGYCUBE,
		GEO_LINE,
		GEO_BG,
		GEO_TICTACTOE,
		GEO_CROSS,
		GEO_CIRCLE,
		GEO_REVERSI,
		GEO_BLACK,
		GEO_WHITE,
		GEO_TOOFULL,
		GEO_FULL,
		GEO_HUNGRY,
		GEO_DEAD,
		GEO_SHARK,
		GEO_FISHFOOD,
		GEO_CRAZY,
		GEO_HAPPY,
		GEO_CHESSBOARD,
		GEO_QUEEN,
		GEO_KNIGHT,
		GEO_WHITEQUAD,
		GEO_WALL,
		GEO_FLOOR,
		GEO_AGENT,
		GEO_WAYPOINT,
		GEO_WHITEHEX,
		GEO_REVERSIBOARD4x4,
		GEO_REVERSIBOARD,
		GEO_REVERSIWHITE,
		GEO_REVERSIBLACK,
		GEO_FLAPPYBG,
		GEO_SIDEBAR,
		GEO_CHARACTER,
		GEO_PIPE,
		GEO_BASEBLUE,
		GEO_BASERED,
		GEO_SPAWNERBLUE,
		GEO_SPAWNERRED,
		GEO_ATTACKER,
		GEO_RANGED,
		GEO_RANGEDRIGHT,
		GEO_SUPPORT,
		GEO_MECHANIC,
		GEO_MORTAR,
		GEO_TANK,
		GEO_MORBOMB,
		GEO_ATTACKER1_FLEEING,
		GEO_ATTACKER1_STAY_STRONG,
		GEO_ATTACKER1_NEAR_DEATH,
		GEO_RANGE2_NEAR_DEATH,
		GEO_RANGE2_PANIC,
		GEO_RANGE1_NEAR_DEATH,
		GEO_RANGE1_HURT,
		GEO_RANGE1_PANIC,
		GEO_RANGE1_HEALTHY,
		GEO_SUPPORT1_HEALING,
		GEO_SUPPORT1_HIDING,
		GEO_SUPPORT1_HEALTHY,
		GEO_SUPPORT1_HURT,
		GEO_SUPPORT1_URGENT_HEALING,
		GEO_SUPPORT2_HIDING,
		GEO_SUPPORT2_URGENT_HEALING,
		GEO_SUPPORT2_HEALING,
		GEO_SUPPORT2_HURT,
		GEO_SUPPORT2_HEALTHY,
		GEO_MECHANIC2_HEALTHY,
		GEO_MECHANIC2_GOLD,
		GEO_MECHANIC2_BUILDING,
		GEO_MECHANIC2_HURT,
		GEO_MECHANIC1_GOLD,
		GEO_MECHANIC1_HIDING,
		GEO_MECHANIC2_HIDING,
		GEO_MECHANIC1_HEALTHY,
		GEO_MECHANIC1_HURT,
		GEO_MECHANIC1_BUILDING,
		GEO_TANK1_PANIC,
		GEO_TANK1_HEALTHY,
		GEO_RANGE2_HEALTHY,
		GEO_TANK1_BOMB,
		GEO_MORTAR1_HEALTHY,
		GEO_MORTAR1_PANIC,
		GEO_MORTAR2_HEALTHY,
		GEO_MORTAR2_PANIC,
		GEO_TANK2_BOMB,
		GEO_TANK2_HEALTHY,
		GEO_TANK2_PANIC,
		GEO_GOLDENORB,
		GEO_ATTACKER1_HEALTHY,
		GEO_RANGE2_HURT,
		GEO_ATTACKER2_HEALTHY,
		GEO_ATTACKER2_FLEEING,
		GEO_ATTACKER2_STAY_STRONG,
		GEO_ATTACKER2_HELPING,
		GEO_ATTACKER2_NEAR_DEATH,
		GEO_ATTACKER1_HELPING,
		GEO_BULLET1,
		GEO_BULLET2,
		GEO_ORE,
		NUM_GEOMETRY,
	};
public:
	SceneBase();
	~SceneBase();

	virtual void Init();
	virtual void Update(double dt);
	virtual void Render();
	virtual void Exit();

	void RenderText(Mesh* mesh, std::string text, Color color);
	void RenderTextOnScreen(Mesh* mesh, std::string text, Color color, float size, float x, float y);
	void RenderMesh(Mesh *mesh, bool enableLight);
protected:
	unsigned m_vertexArrayID;
	Mesh* meshList[NUM_GEOMETRY];
	unsigned m_programID;
	unsigned m_parameters[U_TOTAL];

	Camera camera;

	MS modelStack;
	MS viewStack;
	MS projectionStack;

	Light lights[1];

	bool bLightEnabled;

	float fps;
};

#endif